# Bravos Trade Status Viewer

Shows all Bravos trade alerts with parsed fields, order status, and whether the position is currently open in IBKR (paper account).

**Requires:** Cloud SQL Auth Proxy running on 127.0.0.1:5432, `BRAVOS_DB_PASSWORD` set in environment.

In [1]:
import os
import pandas as pd
import psycopg2

conn = psycopg2.connect(
    host=os.environ.get('BRAVOS_DB_HOST', '127.0.0.1'),
    port=int(os.environ.get('BRAVOS_DB_PORT', '5432')),
    dbname=os.environ.get('BRAVOS_DB_NAME', 'bravos_trading'),
    user=os.environ.get('BRAVOS_DB_USER', 'bravos'),
    password=os.environ.get('BRAVOS_DB_PASSWORD', ''),
)
print('Connected to bravos_trading')

Connected to bravos_trading

In [2]:
query = """
WITH latest_gate AS (
    SELECT DISTINCT ON (signal_id)
        signal_id, gate_passed, checked_at
    FROM risk_gate_log
    ORDER BY signal_id, checked_at DESC
),
latest_order AS (
    SELECT DISTINCT ON (signal_id)
        signal_id, status AS order_status, fill_price, quantity AS order_qty
    FROM orders
    ORDER BY signal_id, created_at DESC
),
open_lots AS (
    -- Internal open lots per ticker
    SELECT ticker, SUM(quantity) AS open_qty_internal
    FROM position_lots
    WHERE lot_closed_at IS NULL
    GROUP BY ticker
),
ibkr_snapshot AS (
    -- Most recent broker position snapshot per ticker
    SELECT DISTINCT ON (ticker)
        ticker, position AS ibkr_qty, avg_cost AS ibkr_avg_cost, snapshot_at
    FROM broker_positions_snapshot
    ORDER BY ticker, snapshot_at DESC
)
SELECT
    s.id                                            AS signal_id,
    s.created_at AT TIME ZONE 'UTC'                 AS alert_date,
    s.ticker,
    s.action_type,
    s.weight_from,
    s.weight_to,
    s.reference_price,
    s.stop_loss,
    s.take_profits,
    s.confidence,
    s.post_title,
    s.post_url,
    CASE
        WHEN lo.order_status IS NULL AND lg.gate_passed IS NULL THEN 'not_executed'
        WHEN lg.gate_passed = FALSE                             THEN 'risk_blocked'
        WHEN lo.order_status IS NULL                           THEN 'no_order'
        ELSE lo.order_status
    END                                             AS order_status,
    lo.order_qty,
    lo.fill_price,
    ol.open_qty_internal,
    ib.ibkr_qty,
    ib.ibkr_avg_cost,
    ib.snapshot_at                                  AS ibkr_snapshot_at,
    CASE
        WHEN ib.ibkr_qty IS NOT NULL AND ib.ibkr_qty != 0 THEN 'OPEN'
        WHEN ib.ibkr_qty = 0                               THEN 'CLOSED'
        ELSE 'UNKNOWN'
    END                                             AS ibkr_position_status
FROM signals s
LEFT JOIN latest_gate   lg ON lg.signal_id = s.id
LEFT JOIN latest_order  lo ON lo.signal_id = s.id
LEFT JOIN open_lots     ol ON ol.ticker    = s.ticker
LEFT JOIN ibkr_snapshot ib ON ib.ticker    = s.ticker
WHERE s.post_title != 'test'
  AND s.ticker NOT IN ('TEST', 'BADTKR')
  AND s.ticker IS NOT NULL
ORDER BY s.created_at DESC;
"""

df = pd.read_sql(query, conn)
df['alert_date'] = pd.to_datetime(df['alert_date']).dt.strftime('%Y-%m-%d %H:%M UTC')
print(f'{len(df)} signals loaded')
df.head()

181 signals loaded

/tmp/ipykernel_2548/1136138880.py:69: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

,signal_id,alert_date,ticker,action_type,weight_from,weight_to,reference_price,stop_loss,take_profits,confidence,post_title,post_url,order_status,order_qty,fill_price,open_qty_internal,ibkr_qty,ibkr_avg_cost,ibkr_snapshot_at,ibkr_position_status
0,2310,2026-06-02 05:01 UTC,HBM,open,0.0,3.0,29.51,25.45,"[31.50, 41.50, 45.00]",high,Initiating Long on Hudbay Minerals Inc ($HBM) ...,https://bravosresearch.com/portfolio-update/in...,not_executed,NaN,None,None,NaN,NaN,NaT,UNKNOWN
1,2308,2026-05-30 06:14 UTC,NVDA,open,0.0,5.0,216.26,195.00,"[250.00, 275.00, 300.00]",high,Initiating Long on Nvidia ($NVDA) | Breakout,https://bravosresearch.com/news-feed/initiatin...,not_executed,NaN,None,None,NaN,NaN,NaT,UNKNOWN
2,2306,2026-05-30 06:11 UTC,NTRA,open,NaN,NaN,NaN,200.00,"[265.00, 285.00, 300.00]",medium,Initiating Long on Natera Inc ($NTRA) | Breakout,https://bravosresearch.com/news-feed/initiatin...,not_executed,NaN,None,None,NaN,NaN,NaT,UNKNOWN
3,2304,2026-05-30 06:08 UTC,CB,close,NaN,0.0,313.44,NaN,[],high,Closing Chubb Limited ($CB) | Breakdown,https://bravosresearch.com/news-feed/chubb-lim...,not_executed,NaN,None,None,NaN,NaN,NaT,UNKNOWN
4,2302,2026-05-30 06:04 UTC,UNP,close,NaN,0.0,262.22,NaN,[],high,Closing Union Pacific Corperation ($UNP) | Bre...,https://bravosresearch.com/news-feed/closing-u...,not_executed,NaN,None,None,NaN,NaN,NaT,UNKNOWN

## All trade alerts — most recent first

In [3]:
display_cols = [
    'alert_date', 'ticker', 'action_type', 'weight_from', 'weight_to',
    'reference_price', 'stop_loss', 'take_profits', 'confidence',
    'order_status', 'fill_price',
    'ibkr_position_status', 'ibkr_qty', 'ibkr_avg_cost', 'post_title'
]

pd.set_option('display.max_colwidth', 60)
pd.set_option('display.max_rows', 200)
df[display_cols]

,alert_date,ticker,action_type,weight_from,weight_to,reference_price,stop_loss,take_profits,confidence,order_status,fill_price,ibkr_position_status,ibkr_qty,ibkr_avg_cost,post_title
0,2026-06-02 05:01 UTC,HBM,open,0.0,3.0,29.51,25.45,"[31.50, 41.50, 45.00]",high,not_executed,None,UNKNOWN,NaN,NaN,Initiating Long on Hudbay Minerals Inc ($HBM) | Breakout
1,2026-05-30 06:14 UTC,NVDA,open,0.0,5.0,216.26,195.00,"[250.00, 275.00, 300.00]",high,not_executed,None,UNKNOWN,NaN,NaN,Initiating Long on Nvidia ($NVDA) | Breakout
2,2026-05-30 06:11 UTC,NTRA,open,NaN,NaN,NaN,200.00,"[265.00, 285.00, 300.00]",medium,not_executed,None,UNKNOWN,NaN,NaN,Initiating Long on Natera Inc ($NTRA) | Breakout
3,2026-05-30 06:08 UTC,CB,close,NaN,0.0,313.44,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Chubb Limited ($CB) | Breakdown
4,2026-05-30 06:04 UTC,UNP,close,NaN,0.0,262.22,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Union Pacific Corperation ($UNP) | Breakdown
5,2026-05-30 05:59 UTC,YPF,partial_close,3.0,2.0,53.50,NaN,[],high,no_order,None,UNKNOWN,NaN,NaN,Booking Partial Profits in YPF Sociedad Anonima ($YPF) |...
6,2026-05-30 05:55 UTC,IYT,open,NaN,NaN,84.12,76.50,[84.12],medium,not_executed,None,UNKNOWN,NaN,NaN,Initiating Long on iShares Transportation Average ETF ($...
7,2026-05-30 05:52 UTC,UNP,open,0.0,3.0,271.37,257.00,[271.37],high,not_executed,None,UNKNOWN,NaN,NaN,Initiating Long on Union Pacific Corporation ($UNP) | Po...
8,2026-05-30 05:48 UTC,XLF,open,NaN,NaN,NaN,47.50,[51.96],medium,not_executed,None,UNKNOWN,NaN,NaN,Initiating Long on Financial Select Sector SPDR Fund ($X...
9,2026-05-30 05:46 UTC,ASML,open,NaN,NaN,1.00,1420.00,"[1800.00, 2000.00, 2300.00]",medium,not_executed,None,UNKNOWN,NaN,NaN,Initiating Long on ASML Holdings ($ASML) | Breakout
10,2026-05-30 05:43 UTC,DE,close,NaN,0.0,530.63,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Deere & Company ($DE) | Breakdown
11,2026-05-30 05:41 UTC,XME,close,NaN,0.0,113.07,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing SPDR S&P Metals and Mining ETF ($XME) | Breakdown
12,2026-05-30 05:39 UTC,SMH,close,NaN,0.0,541.22,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing VanEck Semiconductor ETF ($SMH) | Breakdown
13,2026-05-30 05:38 UTC,XEL,close,NaN,0.0,78.17,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Xcel Energy ($XEL) | Breakdown
14,2026-05-30 05:36 UTC,YPF,open,NaN,NaN,45.83,41.50,[45.83],medium,not_executed,None,UNKNOWN,NaN,NaN,Initiating Long on YPF Sociedad Anonima ($YPF) | Potenti...
15,2026-05-30 05:34 UTC,MU,close,NaN,0.0,704.51,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Micron Technology Inc ($MU) | Breakdown
16,2026-05-30 05:32 UTC,NEE,close,NaN,0.0,89.00,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing NextEra Energy Inc ($NEE) | Breakdown
17,2026-05-30 05:19 UTC,BFLY,close,NaN,0.0,4.25,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Butterfly Network ($BFLY) | Breakdown
18,2026-05-30 05:17 UTC,TEVA,partial_close,4.0,3.0,36.94,NaN,[],high,no_order,None,UNKNOWN,NaN,NaN,Booking Partial Profits in Teva Pharmaceutical Limited (...
19,2026-05-30 05:14 UTC,ANDE,close,NaN,0.0,66.74,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Andersons Inc ($ANDE) | Breakdown
20,2026-05-30 05:13 UTC,CVS,open,NaN,NaN,85.64,79.00,[85.64],medium,not_executed,None,UNKNOWN,NaN,NaN,Initiating Long on CVS Health Corporation ($CVS) | Breakout
21,2026-05-30 05:09 UTC,ANDE,partial_close,4.0,3.0,81.10,NaN,[],high,no_order,None,UNKNOWN,NaN,NaN,Booking Partial Profits on Andersons Inc ($ANDE) | Profi...
22,2026-05-30 05:08 UTC,MU,partial_close,2.0,1.0,633.72,NaN,[],high,no_order,None,UNKNOWN,NaN,NaN,Booking Partial Profits on Micron Technology Inc ($MU) |...
23,2026-05-30 05:04 UTC,MU,partial_close,3.0,2.0,589.75,NaN,[],high,no_order,None,UNKNOWN,NaN,NaN,Booking Partial Profits on Micron Technology Inc ($MU) |...
24,2026-05-29 08:05 UTC,APO,close,NaN,0.0,144.50,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,"Closing Apollo Global Management, Inc. ($APO) | Breakdown"
25,2026-05-29 08:00 UTC,NRG,partial_close,3.0,2.0,141.94,NaN,[],high,SUBMITTED,None,UNKNOWN,NaN,NaN,"Booking Profits on NRG Energy, Inc. ($NRG) | 38.84% Profit"
26,2026-05-29 07:59 UTC,EQT,close,NaN,0.0,51.30,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing EQT Corporation ($EQT) | Raising Cash
27,2026-05-29 07:57 UTC,ZIJMF,close,NaN,0.0,2.21,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Zijin Mining Group Company Ltd. ($ZIJMF) | 17.55...
28,2026-05-29 07:56 UTC,SPOT,NaN,NaN,NaN,605.99,NaN,[],low,not_executed,None,UNKNOWN,NaN,NaN,Long Spotify Technology ($SPOT) | Breakout Above Downtrend
29,2026-05-29 07:54 UTC,NRG,NaN,NaN,NaN,102.23,NaN,[],low,not_executed,None,UNKNOWN,NaN,NaN,"Long NRG Energy, Inc. ($NRG) | Break Above Downtrend"
30,2026-05-29 07:53 UTC,WPM,close,NaN,0.0,80.75,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Wheaton Precious Metals Corp ($WPM) | 43.58% Profit
31,2026-05-29 07:51 UTC,AEM,close,NaN,0.0,116.55,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Agnico Eagle Mines Limited ($AEM) | 45.96% Profit
32,2026-05-29 07:50 UTC,UGL,close,NaN,0.0,143.50,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Proshares Ultra Gold (UGL) | 48.97% Profit
33,2026-05-29 07:48 UTC,HDB,NaN,NaN,NaN,69.20,NaN,[],low,not_executed,None,UNKNOWN,NaN,NaN,Long HDFC Bank Limited ($HDB) | Breakout from Downtrend
34,2026-05-29 07:47 UTC,UAMY,partial_close,3.0,2.0,3.24,NaN,[],high,SUBMITTED,None,UNKNOWN,NaN,NaN,Booking Profits on United States Antimony Corporation ($...
35,2026-05-29 07:45 UTC,JD,close,NaN,0.0,38.83,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,"Closing JD.com, Inc. ($JD) | Break of Bullish Structure"
36,2026-05-29 07:44 UTC,ADMA,NaN,NaN,NaN,20.00,NaN,[],low,not_executed,None,UNKNOWN,NaN,NaN,Long ADMA Biologics ($ADMA) | Breakout from Downtrend
37,2026-05-29 07:41 UTC,ADMA,close,NaN,0.0,18.04,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing ADMA Biologics ($ADMA) | Break of Bullish Structure
38,2026-05-29 07:40 UTC,MDU,close,NaN,0.0,16.02,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,"Closing MDU Resources Group, Inc. ($MDU) | Stop Loss Hit"
39,2026-05-29 07:38 UTC,XLE,close,NaN,0.0,89.65,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Energy Sector ($XLE) | Reducing Risk
40,2026-05-29 07:37 UTC,CCJ,close,NaN,0.0,42.31,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Cameco Corporation ($CCJ) | Reducing Risk
41,2026-05-29 07:36 UTC,TPB,close,NaN,0.0,60.52,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Turning Point Brands Inc. ($TPB) | Reducing Risk
42,2026-05-29 07:33 UTC,DASH,close,NaN,0.0,183.95,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing DoorDash ($DASH) | False Breakout
43,2026-05-29 07:31 UTC,TRMB,close,NaN,0.0,69.10,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Trimble Inc. ($TRMB) | Break of Support
44,2026-05-29 07:30 UTC,MWA,close,NaN,0.0,26.70,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Mueller Water Products ($MWA) | False Breakout
45,2026-05-29 07:29 UTC,UAMY,NaN,NaN,NaN,2.05,NaN,[],low,not_executed,None,UNKNOWN,NaN,NaN,Long United States Antimony Corporation ($UAMY) | Bull F...
46,2026-05-29 07:27 UTC,ADMA,NaN,NaN,NaN,19.52,NaN,[],low,not_executed,None,UNKNOWN,NaN,NaN,Long ADMA Biologics ($ADMA) | Inverse Head and Shoulders...
47,2026-05-29 07:26 UTC,EQT,NaN,NaN,NaN,52.98,NaN,[],low,not_executed,None,UNKNOWN,NaN,NaN,Long EQT Corporation ($EQT) | Bottoming Pattern
48,2026-05-29 07:24 UTC,UPRO,NaN,NaN,NaN,79.63,NaN,[],low,not_executed,None,UNKNOWN,NaN,NaN,Long SP500 3x Leveraged ETF ($UPRO) | Buy the Dip
49,2026-05-29 07:22 UTC,SHOP,NaN,NaN,NaN,108.22,NaN,[],low,not_executed,None,UNKNOWN,NaN,NaN,Long Shopify Inc. ($SHOP) | Retesting Breakout
50,2026-05-29 07:21 UTC,MDU,NaN,NaN,NaN,17.08,NaN,[],low,not_executed,None,UNKNOWN,NaN,NaN,"Long MDU Resources Group, Inc. ($MDU) | Channel Support"
51,2026-05-29 07:19 UTC,CCJ,NaN,NaN,NaN,45.26,NaN,[],low,not_executed,None,UNKNOWN,NaN,NaN,Long Cameco Corporation ($CCJ) | Rising Price Channel Su...
52,2026-05-29 07:17 UTC,SHAK,NaN,NaN,NaN,109.20,NaN,[],low,not_executed,None,UNKNOWN,NaN,NaN,"Long Shake Shack, Inc. ($SHAK) | Inverse Head and Should..."
53,2026-05-29 07:16 UTC,YMM,close,NaN,0.0,10.80,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Full Truck Alliance Co. Ltd. ($YMM) | 7.87% Profit
54,2026-05-29 07:15 UTC,AMZN,close,NaN,0.0,196.59,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Amazon ($AMZN) | Stop-loss Hit
55,2026-05-29 07:13 UTC,NGVC,close,NaN,0.0,46.88,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Natural Grocers by Vitamin Cottage ($NGVC) | Bre...
56,2026-05-29 07:12 UTC,GOOGL,close,NaN,0.0,185.96,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Alphabet ($GOOGL) | Break Below Uptrend Line
57,2026-05-29 07:11 UTC,XLE,NaN,NaN,NaN,90.78,NaN,[],low,not_executed,None,UNKNOWN,NaN,NaN,Long Energy Sector ($XLE) | False Breakdown
58,2026-05-29 07:09 UTC,BYDDF,partial_close,5.0,3.0,46.90,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Booking Profits on BYD ($BYDDF) | Sharp Run-Up
59,2026-05-29 07:08 UTC,TRMB,NaN,NaN,NaN,75.75,NaN,[],low,not_executed,None,UNKNOWN,NaN,NaN,Long Trimble Inc. ($TRMB) | Break Above Downtrend
60,2026-05-29 07:07 UTC,HBM,close,NaN,0.0,8.97,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Hudbay Minerals Inc. ($HBM) | Stoploss Hit
61,2026-05-29 07:06 UTC,JD,NaN,NaN,NaN,39.25,NaN,[],low,not_executed,None,UNKNOWN,NaN,NaN,"Long JD.com, Inc. ($JD) | China Catch Up Trade"
62,2026-05-29 07:04 UTC,NTRA,NaN,NaN,NaN,169.59,NaN,[],low,not_executed,None,UNKNOWN,NaN,NaN,Long Natera Inc. ($NTRA) | Biotech Sector Trade
63,2026-05-29 07:03 UTC,XBI,close,NaN,0.0,94.50,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing SPDR S&P Biotech ETF ($XBI) | Stoploss Hit
64,2026-05-29 07:02 UTC,TPB,open,NaN,NaN,67.16,62.29,[67.16],medium,not_executed,None,UNKNOWN,NaN,NaN,Initiating Long on Turning Point Brands Inc. ($TPB) | Br...
65,2026-05-29 07:00 UTC,HBM,open,NaN,NaN,8.97,8.31,[8.97],medium,not_executed,None,UNKNOWN,NaN,NaN,Initiating Long on Hudbay Minerals Inc. ($HBM) | Multi-M...
66,2026-05-29 06:59 UTC,LMND,open,NaN,NaN,36.10,33.33,[36.10],medium,not_executed,None,UNKNOWN,NaN,NaN,Initiating Long on Lemonade Inc. ($LMND) | Break Above D...
67,2026-05-29 06:58 UTC,UGL,partial_close,5.0,3.0,110.11,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Booking Profits on Proshares Ultra Gold (UGL)
68,2026-05-29 06:57 UTC,AEM,partial_close,5.0,3.0,99.27,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Booking Profits on Agnico Eagle Mines Limited ($AEM) | P...
69,2026-05-29 06:55 UTC,XBI,open,NaN,NaN,94.50,88.17,[94.50],medium,not_executed,None,UNKNOWN,NaN,NaN,Initiating Long on Biotech ETF ($XBI) | Breakout from Fa...
70,2026-05-29 06:54 UTC,NGVC,open,NaN,NaN,46.88,43.20,[46.88],medium,not_executed,None,UNKNOWN,NaN,NaN,Initiating Long on Natural Grocers by Vitamin Cottage ($...
71,2026-05-29 06:53 UTC,HES,close,NaN,0.0,138.28,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Long on Hess Corporation ($HES) | False Breakout
72,2026-05-29 06:51 UTC,HES,open,NaN,NaN,145.34,138.00,[145.34],medium,not_executed,None,UNKNOWN,NaN,NaN,Initiating Long on Hess Corporation ($HES) | Break Above...
73,2026-05-29 06:49 UTC,BACHF,open,NaN,NaN,4.02,3.78,[],medium,not_executed,None,UNKNOWN,NaN,NaN,Initiating Long on Bank of China ($3988 / $BACHF on OTC)...
74,2026-05-29 06:48 UTC,ZIJMF,open,NaN,NaN,1.88,1.64,[],medium,not_executed,None,UNKNOWN,NaN,NaN,Initiating Long on Zijin Mining Group Company Ltd. ($ZIJ...
75,2026-05-29 06:46 UTC,ETR,close,NaN,0.0,77.00,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Long on Entergy Corporation ($ETR) | Breaking Be...
76,2026-05-29 06:45 UTC,ANET,close,NaN,0.0,107.55,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Long Position on Arista Networks ($ANET) | Break...
77,2026-05-29 06:44 UTC,WIX,close,NaN,0.0,228.37,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Long Position on Wix.com Ltd. ($WIX) | Break of ...
78,2026-05-29 06:42 UTC,TLN,close,NaN,0.0,248.47,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Long on Talen Energy Corporation ($TLN)
79,2026-05-29 06:41 UTC,GEV,close,NaN,0.0,437.64,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Long on GE Vernova Inc (GEV)
80,2026-05-29 06:40 UTC,CNC,close,NaN,0.0,64.90,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Short on Centene Corporation ($CNC) | Stop-Loss Hit
81,2026-05-29 06:39 UTC,ETR,partial_close,5.0,3.0,75.24,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Booking Profits on Entergy Corporation ($ETR) | Testing ...
82,2026-05-29 06:38 UTC,GEV,partial_close,5.0,3.0,372.20,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Booking Profits on GE Vernova ($GEV) | Testing Channel R...
83,2026-05-29 06:36 UTC,ANET,partial_close,5.0,3.0,107.55,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Booking Profits on Arista Networks Inc. ($ANET) | +20%
84,2026-05-29 06:35 UTC,TLN,partial_close,NaN,NaN,246.12,NaN,[],medium,not_executed,None,UNKNOWN,NaN,NaN,Booking Partial Profits on Talen Energy Corporation ($TL...
85,2026-05-29 06:34 UTC,COIN,NaN,NaN,NaN,273.52,NaN,[],low,not_executed,None,UNKNOWN,NaN,NaN,Long Coinbase Global Inc. ($COIN) | Breakout of Inverse ...
86,2026-05-29 06:32 UTC,WGS,close,NaN,0.0,89.62,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing GeneDx Holdings Corp ($WGS) | Break Down Below B...
87,2026-05-29 06:30 UTC,YMM,NaN,NaN,NaN,10.80,NaN,[],low,not_executed,None,UNKNOWN,NaN,NaN,Long Full Truck Alliance Co. Ltd. ($YMM) | Break Above B...
88,2026-05-29 06:28 UTC,WIX,NaN,NaN,NaN,228.37,NaN,[],low,not_executed,None,UNKNOWN,NaN,NaN,Long Wix.com Ltd ($WIX) | Break Above Consolidation
89,2026-05-29 06:27 UTC,KVYO,close,NaN,0.0,39.30,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Long on Klaviyo Inc ($KVYO) | Break of Rising Ch...
90,2026-05-29 06:26 UTC,FI,close,NaN,0.0,201.59,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Long on Fiserv Inc ($FI) | Break of Uptrend
91,2026-05-29 06:25 UTC,XLE,close,NaN,0.0,89.30,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Short on Energy Stocks (XLE) | False Breakdown
92,2026-05-29 06:24 UTC,UGL,NaN,NaN,NaN,96.33,NaN,[],low,not_executed,None,UNKNOWN,NaN,NaN,Long Proshares Ultra Gold (UGL) | Constructive Price Action
93,2026-05-29 06:22 UTC,GEV,NaN,NaN,NaN,372.20,NaN,[],low,not_executed,None,UNKNOWN,NaN,NaN,Long GE Vernova Inc (GEV) | Strong Breakout
94,2026-05-29 06:20 UTC,WGS,NaN,NaN,NaN,89.62,NaN,[],low,not_executed,None,UNKNOWN,NaN,NaN,Long GeneDx Holdings Corp (WGS) | Break Above Consolidation
95,2026-05-29 06:19 UTC,AFRM,NaN,NaN,NaN,61.29,NaN,[],low,not_executed,None,UNKNOWN,NaN,NaN,Long Affirm Holdings Inc. (AFRM) | Breakout of Basing Pa...
96,2026-05-29 06:18 UTC,TCEHY,close,NaN,0.0,50.04,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Tencent Holdings Ltd. ($TCEHY) | Break Below Bul...
97,2026-05-29 06:17 UTC,SPXS,close,NaN,0.0,5.95,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing S&P 500 Short Hedge ($SPXS) | Less Over-Extended...
98,2026-05-29 06:16 UTC,SPXS,partial_close,NaN,NaN,6.43,NaN,[],medium,not_executed,None,UNKNOWN,NaN,NaN,Booking Partial Profits on S&P 500 Short Hedge ($SPXS) |...
99,2026-05-29 06:15 UTC,TSLA,close,NaN,0.0,420.80,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Long Tesla ($TSLA) | Break of Momentum
100,2026-05-29 06:13 UTC,WPM,add,NaN,NaN,56.24,51.75,[],medium,not_executed,None,UNKNOWN,NaN,NaN,Increasing Exposure to Wheaton Precious Metals ($WPM) | ...
101,2026-05-29 06:12 UTC,AEM,NaN,NaN,NaN,79.85,NaN,[],low,not_executed,None,UNKNOWN,NaN,NaN,Long Agnico Eagle Mines Limited ($AEM) | Gold Miner Trade
102,2026-05-29 06:11 UTC,SONY,NaN,NaN,NaN,21.34,NaN,[],low,not_executed,None,UNKNOWN,NaN,NaN,Long Sony Group Corporation ($SONY) | Breakout of Long T...
103,2026-05-29 06:10 UTC,TLN,NaN,NaN,NaN,203.91,NaN,[],low,not_executed,None,UNKNOWN,NaN,NaN,Long Talen Energy Corporation ($TLN) | Utilities Stock T...
104,2026-05-29 06:09 UTC,TCOM,close,NaN,0.0,72.54,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Long Position on Trip.com ($TCOM) | Chinese Stoc...
105,2026-05-29 06:06 UTC,ETH,close,NaN,0.0,2.00,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Ethereum ($ETH) | Break of Primary Upward Channel
106,2026-05-29 06:04 UTC,SPXS,NaN,NaN,NaN,5.98,NaN,[],low,not_executed,None,UNKNOWN,NaN,NaN,Initiating Short Hedge on the SP500: Long S&P 500 Bear 3...
107,2026-05-29 06:03 UTC,SHAK,close,NaN,0.0,114.00,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Long Shake Shack Inc. ($SHAK) | + 14%
108,2026-05-29 06:02 UTC,SLV,close,NaN,0.0,25.13,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Long Silver ($SLV) | Break of Support
109,2026-05-29 06:01 UTC,GOOGL,NaN,NaN,NaN,185.96,NaN,[],low,not_executed,None,UNKNOWN,NaN,NaN,Long Alphabet ($GOOGL) |Tech Trade Following Historic VI...
110,2026-05-29 06:00 UTC,ANET,NaN,NaN,NaN,107.55,NaN,[],low,not_executed,None,UNKNOWN,NaN,NaN,Long Arista Networks ($ANET) |Tech Trade Following Histo...
111,2026-05-29 05:59 UTC,TSLA,NaN,NaN,NaN,420.80,NaN,[],low,not_executed,None,UNKNOWN,NaN,NaN,Long Tesla Inc. ($TSLA) | Tech Trade Following Historic ...
112,2026-05-29 05:57 UTC,ETH,partial_close,5.0,2.0,2.00,NaN,[],high,SUBMITTED,None,UNKNOWN,NaN,NaN,Booking Profits on Ethereum (ETH) | Break of Short Term ...
113,2026-05-29 05:10 UTC,CPER,partial_close,5.0,3.0,5.83,NaN,[],high,SUBMITTED,None,UNKNOWN,NaN,NaN,Booking Partial Profits on Copper ($CPER) | Profit Booking
114,2026-05-23 05:44 UTC,CSCO,close,NaN,0.0,76.20,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Cisco (CSCO) | Breakdown
115,2026-05-23 05:21 UTC,NWG,close,NaN,0.0,9.60,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Long NatWest Group ($NWG) | Potential Local Top
116,2026-05-23 05:21 UTC,TCOM,NaN,NaN,NaN,72.54,NaN,[],low,not_executed,None,UNKNOWN,NaN,NaN,Long Trip.com ($TCOM) | Chinese Tech Stock
117,2026-05-23 05:21 UTC,KVYO,NaN,NaN,NaN,42.00,NaN,[],low,not_executed,None,UNKNOWN,NaN,NaN,Long Klaviyo Inc. ($KVYO) | Breakout of Basing Pattern
118,2026-05-23 05:20 UTC,YMM,close,NaN,0.0,11.65,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Long Full Truck Alliance ($YMM) | Break of Chann...
119,2026-05-23 05:20 UTC,FI,NaN,NaN,NaN,206.49,NaN,[],low,not_executed,None,UNKNOWN,NaN,NaN,Long Fiserv Inc ($FI) | Financial Sector Trade
120,2026-05-23 05:20 UTC,ETR,NaN,NaN,NaN,75.24,NaN,[],low,not_executed,None,UNKNOWN,NaN,NaN,Long Entergy Corporation ($ETR) | Utilities Sector Trade
121,2026-05-23 05:20 UTC,XBI,close,NaN,0.0,99.48,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Biotech ETF ($XBI) | Key Moving Averages Breakdown
122,2026-05-23 05:20 UTC,TUR,close,NaN,0.0,33.79,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Long Position on Turkish Stocks ($TUR) | Break o...
123,2026-05-23 05:20 UTC,YMM,NaN,NaN,NaN,11.65,NaN,[],low,not_executed,None,UNKNOWN,NaN,NaN,Long Full Truck Alliance ($YMM) | Chinese Stock
124,2026-05-23 05:20 UTC,OWL,NaN,NaN,NaN,23.50,NaN,[],low,not_executed,None,UNKNOWN,NaN,NaN,Long Blue Owl Capital Inc. ($OWL) | Breakout of Long Ter...
125,2026-05-23 05:20 UTC,AMZN,partial_close,NaN,NaN,196.59,NaN,[],medium,not_executed,None,UNKNOWN,NaN,NaN,Booking Profits on Amazon.com Inc. ($AMZN)
126,2026-05-23 05:20 UTC,SHAK,partial_close,NaN,NaN,114.00,NaN,[],medium,not_executed,None,UNKNOWN,NaN,NaN,Booking Profits on Shake Shack Inc. ($SHAK) | + 19.8%
127,2026-05-23 05:20 UTC,NWG,partial_close,NaN,NaN,9.60,NaN,[],medium,not_executed,None,UNKNOWN,NaN,NaN,Booking Profits on NatWest Group plc ($NWG) | Price at C...
128,2026-05-23 05:20 UTC,BYDDF,NaN,NaN,NaN,36.30,NaN,[],low,not_executed,None,UNKNOWN,NaN,NaN,Long BYD ($BYDDF) | Chinese Stock Trade
129,2026-05-23 05:20 UTC,XBI,NaN,NaN,NaN,99.48,NaN,[],low,not_executed,None,UNKNOWN,NaN,NaN,Long Biotech ($XBI) | Break Out of Short-Term Consolidation
130,2026-05-23 05:20 UTC,TUR,partial_close,NaN,NaN,33.79,NaN,[],medium,not_executed,None,UNKNOWN,NaN,NaN,Booking Profits on Turkish Stocks | Price at Resistance

## Currently open positions in IBKR

In [4]:
open_pos = df[df['ibkr_position_status'] == 'OPEN'].drop_duplicates('ticker')
print(f'{len(open_pos)} tickers with open IBKR positions')
open_pos[['ticker', 'ibkr_qty', 'ibkr_avg_cost', 'ibkr_snapshot_at']].sort_values('ticker')

1 tickers with open IBKR positions

    ticker  ibkr_qty  ibkr_avg_cost                 ibkr_snapshot_at
143   META      36.0         566.96 2026-05-29 07:58:47.158704+00:00

## Signals by order status

In [5]:
df.groupby('order_status').size().rename('count').to_frame()

              count
order_status
SUBMITTED         7
no_order          7
not_executed    167

## High-confidence signals only

In [6]:
high = df[df['confidence'] == 'high']
print(f'{len(high)} high-confidence signals')
high[display_cols]

97 high-confidence signals

,alert_date,ticker,action_type,weight_from,weight_to,reference_price,stop_loss,take_profits,confidence,order_status,fill_price,ibkr_position_status,ibkr_qty,ibkr_avg_cost,post_title
0,2026-06-02 05:01 UTC,HBM,open,0.0,3.0,29.51,25.45,"[31.50, 41.50, 45.00]",high,not_executed,None,UNKNOWN,NaN,NaN,Initiating Long on Hudbay Minerals Inc ($HBM) | Breakout
1,2026-05-30 06:14 UTC,NVDA,open,0.0,5.0,216.26,195.00,"[250.00, 275.00, 300.00]",high,not_executed,None,UNKNOWN,NaN,NaN,Initiating Long on Nvidia ($NVDA) | Breakout
3,2026-05-30 06:08 UTC,CB,close,NaN,0.0,313.44,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Chubb Limited ($CB) | Breakdown
4,2026-05-30 06:04 UTC,UNP,close,NaN,0.0,262.22,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Union Pacific Corperation ($UNP) | Breakdown
5,2026-05-30 05:59 UTC,YPF,partial_close,3.0,2.0,53.50,NaN,[],high,no_order,None,UNKNOWN,NaN,NaN,Booking Partial Profits in YPF Sociedad Anonima ($YPF) |...
7,2026-05-30 05:52 UTC,UNP,open,0.0,3.0,271.37,257.00,[271.37],high,not_executed,None,UNKNOWN,NaN,NaN,Initiating Long on Union Pacific Corporation ($UNP) | Po...
10,2026-05-30 05:43 UTC,DE,close,NaN,0.0,530.63,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Deere & Company ($DE) | Breakdown
11,2026-05-30 05:41 UTC,XME,close,NaN,0.0,113.07,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing SPDR S&P Metals and Mining ETF ($XME) | Breakdown
12,2026-05-30 05:39 UTC,SMH,close,NaN,0.0,541.22,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing VanEck Semiconductor ETF ($SMH) | Breakdown
13,2026-05-30 05:38 UTC,XEL,close,NaN,0.0,78.17,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Xcel Energy ($XEL) | Breakdown
15,2026-05-30 05:34 UTC,MU,close,NaN,0.0,704.51,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Micron Technology Inc ($MU) | Breakdown
16,2026-05-30 05:32 UTC,NEE,close,NaN,0.0,89.00,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing NextEra Energy Inc ($NEE) | Breakdown
17,2026-05-30 05:19 UTC,BFLY,close,NaN,0.0,4.25,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Butterfly Network ($BFLY) | Breakdown
18,2026-05-30 05:17 UTC,TEVA,partial_close,4.0,3.0,36.94,NaN,[],high,no_order,None,UNKNOWN,NaN,NaN,Booking Partial Profits in Teva Pharmaceutical Limited (...
19,2026-05-30 05:14 UTC,ANDE,close,NaN,0.0,66.74,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Andersons Inc ($ANDE) | Breakdown
21,2026-05-30 05:09 UTC,ANDE,partial_close,4.0,3.0,81.10,NaN,[],high,no_order,None,UNKNOWN,NaN,NaN,Booking Partial Profits on Andersons Inc ($ANDE) | Profi...
22,2026-05-30 05:08 UTC,MU,partial_close,2.0,1.0,633.72,NaN,[],high,no_order,None,UNKNOWN,NaN,NaN,Booking Partial Profits on Micron Technology Inc ($MU) |...
23,2026-05-30 05:04 UTC,MU,partial_close,3.0,2.0,589.75,NaN,[],high,no_order,None,UNKNOWN,NaN,NaN,Booking Partial Profits on Micron Technology Inc ($MU) |...
24,2026-05-29 08:05 UTC,APO,close,NaN,0.0,144.50,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,"Closing Apollo Global Management, Inc. ($APO) | Breakdown"
25,2026-05-29 08:00 UTC,NRG,partial_close,3.0,2.0,141.94,NaN,[],high,SUBMITTED,None,UNKNOWN,NaN,NaN,"Booking Profits on NRG Energy, Inc. ($NRG) | 38.84% Profit"
26,2026-05-29 07:59 UTC,EQT,close,NaN,0.0,51.30,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing EQT Corporation ($EQT) | Raising Cash
27,2026-05-29 07:57 UTC,ZIJMF,close,NaN,0.0,2.21,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Zijin Mining Group Company Ltd. ($ZIJMF) | 17.55...
30,2026-05-29 07:53 UTC,WPM,close,NaN,0.0,80.75,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Wheaton Precious Metals Corp ($WPM) | 43.58% Profit
31,2026-05-29 07:51 UTC,AEM,close,NaN,0.0,116.55,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Agnico Eagle Mines Limited ($AEM) | 45.96% Profit
32,2026-05-29 07:50 UTC,UGL,close,NaN,0.0,143.50,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Proshares Ultra Gold (UGL) | 48.97% Profit
34,2026-05-29 07:47 UTC,UAMY,partial_close,3.0,2.0,3.24,NaN,[],high,SUBMITTED,None,UNKNOWN,NaN,NaN,Booking Profits on United States Antimony Corporation ($...
35,2026-05-29 07:45 UTC,JD,close,NaN,0.0,38.83,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,"Closing JD.com, Inc. ($JD) | Break of Bullish Structure"
37,2026-05-29 07:41 UTC,ADMA,close,NaN,0.0,18.04,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing ADMA Biologics ($ADMA) | Break of Bullish Structure
38,2026-05-29 07:40 UTC,MDU,close,NaN,0.0,16.02,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,"Closing MDU Resources Group, Inc. ($MDU) | Stop Loss Hit"
39,2026-05-29 07:38 UTC,XLE,close,NaN,0.0,89.65,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Energy Sector ($XLE) | Reducing Risk
40,2026-05-29 07:37 UTC,CCJ,close,NaN,0.0,42.31,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Cameco Corporation ($CCJ) | Reducing Risk
41,2026-05-29 07:36 UTC,TPB,close,NaN,0.0,60.52,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Turning Point Brands Inc. ($TPB) | Reducing Risk
42,2026-05-29 07:33 UTC,DASH,close,NaN,0.0,183.95,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing DoorDash ($DASH) | False Breakout
43,2026-05-29 07:31 UTC,TRMB,close,NaN,0.0,69.10,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Trimble Inc. ($TRMB) | Break of Support
44,2026-05-29 07:30 UTC,MWA,close,NaN,0.0,26.70,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Mueller Water Products ($MWA) | False Breakout
53,2026-05-29 07:16 UTC,YMM,close,NaN,0.0,10.80,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Full Truck Alliance Co. Ltd. ($YMM) | 7.87% Profit
54,2026-05-29 07:15 UTC,AMZN,close,NaN,0.0,196.59,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Amazon ($AMZN) | Stop-loss Hit
55,2026-05-29 07:13 UTC,NGVC,close,NaN,0.0,46.88,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Natural Grocers by Vitamin Cottage ($NGVC) | Bre...
56,2026-05-29 07:12 UTC,GOOGL,close,NaN,0.0,185.96,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Alphabet ($GOOGL) | Break Below Uptrend Line
58,2026-05-29 07:09 UTC,BYDDF,partial_close,5.0,3.0,46.90,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Booking Profits on BYD ($BYDDF) | Sharp Run-Up
60,2026-05-29 07:07 UTC,HBM,close,NaN,0.0,8.97,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Hudbay Minerals Inc. ($HBM) | Stoploss Hit
63,2026-05-29 07:03 UTC,XBI,close,NaN,0.0,94.50,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing SPDR S&P Biotech ETF ($XBI) | Stoploss Hit
67,2026-05-29 06:58 UTC,UGL,partial_close,5.0,3.0,110.11,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Booking Profits on Proshares Ultra Gold (UGL)
68,2026-05-29 06:57 UTC,AEM,partial_close,5.0,3.0,99.27,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Booking Profits on Agnico Eagle Mines Limited ($AEM) | P...
71,2026-05-29 06:53 UTC,HES,close,NaN,0.0,138.28,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Long on Hess Corporation ($HES) | False Breakout
75,2026-05-29 06:46 UTC,ETR,close,NaN,0.0,77.00,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Long on Entergy Corporation ($ETR) | Breaking Be...
76,2026-05-29 06:45 UTC,ANET,close,NaN,0.0,107.55,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Long Position on Arista Networks ($ANET) | Break...
77,2026-05-29 06:44 UTC,WIX,close,NaN,0.0,228.37,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Long Position on Wix.com Ltd. ($WIX) | Break of ...
78,2026-05-29 06:42 UTC,TLN,close,NaN,0.0,248.47,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Long on Talen Energy Corporation ($TLN)
79,2026-05-29 06:41 UTC,GEV,close,NaN,0.0,437.64,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Long on GE Vernova Inc (GEV)
80,2026-05-29 06:40 UTC,CNC,close,NaN,0.0,64.90,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Short on Centene Corporation ($CNC) | Stop-Loss Hit
81,2026-05-29 06:39 UTC,ETR,partial_close,5.0,3.0,75.24,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Booking Profits on Entergy Corporation ($ETR) | Testing ...
82,2026-05-29 06:38 UTC,GEV,partial_close,5.0,3.0,372.20,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Booking Profits on GE Vernova ($GEV) | Testing Channel R...
83,2026-05-29 06:36 UTC,ANET,partial_close,5.0,3.0,107.55,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Booking Profits on Arista Networks Inc. ($ANET) | +20%
86,2026-05-29 06:32 UTC,WGS,close,NaN,0.0,89.62,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing GeneDx Holdings Corp ($WGS) | Break Down Below B...
89,2026-05-29 06:27 UTC,KVYO,close,NaN,0.0,39.30,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Long on Klaviyo Inc ($KVYO) | Break of Rising Ch...
90,2026-05-29 06:26 UTC,FI,close,NaN,0.0,201.59,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Long on Fiserv Inc ($FI) | Break of Uptrend
91,2026-05-29 06:25 UTC,XLE,close,NaN,0.0,89.30,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Short on Energy Stocks (XLE) | False Breakdown
96,2026-05-29 06:18 UTC,TCEHY,close,NaN,0.0,50.04,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Tencent Holdings Ltd. ($TCEHY) | Break Below Bul...
97,2026-05-29 06:17 UTC,SPXS,close,NaN,0.0,5.95,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing S&P 500 Short Hedge ($SPXS) | Less Over-Extended...
99,2026-05-29 06:15 UTC,TSLA,close,NaN,0.0,420.80,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Long Tesla ($TSLA) | Break of Momentum
104,2026-05-29 06:09 UTC,TCOM,close,NaN,0.0,72.54,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Long Position on Trip.com ($TCOM) | Chinese Stoc...
105,2026-05-29 06:06 UTC,ETH,close,NaN,0.0,2.00,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Ethereum ($ETH) | Break of Primary Upward Channel
107,2026-05-29 06:03 UTC,SHAK,close,NaN,0.0,114.00,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Long Shake Shack Inc. ($SHAK) | + 14%
108,2026-05-29 06:02 UTC,SLV,close,NaN,0.0,25.13,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Long Silver ($SLV) | Break of Support
112,2026-05-29 05:57 UTC,ETH,partial_close,5.0,2.0,2.00,NaN,[],high,SUBMITTED,None,UNKNOWN,NaN,NaN,Booking Profits on Ethereum (ETH) | Break of Short Term ...
113,2026-05-29 05:10 UTC,CPER,partial_close,5.0,3.0,5.83,NaN,[],high,SUBMITTED,None,UNKNOWN,NaN,NaN,Booking Partial Profits on Copper ($CPER) | Profit Booking
114,2026-05-23 05:44 UTC,CSCO,close,NaN,0.0,76.20,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Cisco (CSCO) | Breakdown
115,2026-05-23 05:21 UTC,NWG,close,NaN,0.0,9.60,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Long NatWest Group ($NWG) | Potential Local Top
118,2026-05-23 05:20 UTC,YMM,close,NaN,0.0,11.65,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Long Full Truck Alliance ($YMM) | Break of Chann...
121,2026-05-23 05:20 UTC,XBI,close,NaN,0.0,99.48,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Biotech ETF ($XBI) | Key Moving Averages Breakdown
122,2026-05-23 05:20 UTC,TUR,close,NaN,0.0,33.79,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Long Position on Turkish Stocks ($TUR) | Break o...
132,2026-05-23 05:20 UTC,NXE,close,NaN,0.0,8.67,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing NexGen Energy Ltd. ($NXE) | Stoploss Hit
135,2026-05-23 05:20 UTC,NKE,close,NaN,0.0,81.52,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Short Nike Inc. ($NKE)
139,2026-05-23 05:20 UTC,NTRA,close,NaN,0.0,113.24,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Natera Inc. ($NTRA) | +52% Profit
143,2026-05-23 05:19 UTC,META,close,NaN,0.0,562.93,NaN,[],high,not_executed,None,OPEN,36.0,566.96,Closing Long Meta ($META)
144,2026-05-23 05:19 UTC,TLT,close,NaN,0.0,89.76,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Long Treasury Bond ETF ($TLT) | Rising Yields
145,2026-05-23 05:19 UTC,XBI,close,NaN,0.0,95.86,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Biotech ETF ($XBI) | Break of Support
147,2026-05-23 05:19 UTC,DIS,close,NaN,0.0,96.62,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Short Disney ($DIS) | Breakout
148,2026-05-23 05:19 UTC,TEVA,close,NaN,0.0,NaN,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Teva Pharmaceutical Industries Ltd. ($TEVA) | Fa...
153,2026-05-23 05:19 UTC,EXEL,close,NaN,0.0,25.76,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Exelixis Inc. ($EXEL) | +26.5% Profit
154,2026-05-23 05:19 UTC,INFY,close,NaN,0.0,23.30,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Infosys Ltd. ($INFY) | Stoploss Hit
156,2026-05-23 05:19 UTC,NEE,close,NaN,0.0,NaN,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing NextEra Energy Inc. ($NEE) | Break of Channel Su...
158,2026-05-23 05:19 UTC,NMM,close,NaN,0.0,57.60,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Navios Maritime Partners L.P. ($NMM)
163,2026-05-23 05:19 UTC,GE,close,NaN,0.0,171.87,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Long General Electric ($GE)
166,2026-05-23 05:19 UTC,IWM,close,NaN,0.0,201.96,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Long Small Cap Stocks ($IWM)
169,2026-05-23 05:19 UTC,COMP,close,NaN,0.0,5.75,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,"Closing Compass Inc. ($COMP) | Tap, Tap, Tap, Break"
170,2026-05-23 05:19 UTC,MCHI,close,NaN,0.0,42.32,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Long MSCI China ETF ($MCHI) Locking a +17% Gain ...
171,2026-05-17 06:55 UTC,SMH,partial_close,2.0,1.0,572.84,NaN,[],high,SUBMITTED,None,UNKNOWN,NaN,NaN,Booking Partial Profits on VanEck Semiconductor ETF ($SM...
173,2026-05-17 06:55 UTC,CPER,add,5.0,8.0,37.48,NaN,[],high,no_order,None,UNKNOWN,NaN,NaN,Increasing Exposure to United States Copper Index Fund (...
174,2026-05-17 06:55 UTC,EXEL,add,3.0,6.0,46.78,NaN,[],high,no_order,None,UNKNOWN,NaN,NaN,"Increasing Exposure to Exelixis, Inc ($EXEL) | Breakout"
175,2026-05-17 06:55 UTC,XME,open,0.0,5.0,123.59,112.75,[123.59],high,not_executed,None,UNKNOWN,NaN,NaN,Initiating Long on SPDR S&P Metals and Mining ETF ($XME)...
176,2026-05-17 06:55 UTC,CVS,partial_close,5.0,4.0,96.90,NaN,[],high,SUBMITTED,None,UNKNOWN,NaN,NaN,Booking Partial Profits on CVS Health Corporation ($CVS)...
177,2026-05-17 06:55 UTC,UUUU,close,NaN,0.0,19.50,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing Energy Fuels Inc ($UUUU) | Breakdown
178,2026-05-17 06:55 UTC,CPER,partial_close,8.0,7.0,40.08,NaN,[],high,SUBMITTED,None,UNKNOWN,NaN,NaN,Booking Partial Profits on United States Copper Index Fu...
179,2026-05-17 06:55 UTC,EWZ,close,NaN,0.0,36.11,NaN,[],high,not_executed,None,UNKNOWN,NaN,NaN,Closing iShares MSCI Brazil ETF ($EWZ) | Breakdown
180,2026-05-09 05:57 UTC,EWJ,open,0.0,5.0,92.00,83.50,[92.00],high,not_executed,None,UNKNOWN,NaN,NaN,Initiating Long on iShares MSCI Japan ETF ($EWJ) | Breakout